version: '3.8'

networks:
  monitor-net:
    driver: bridge

services:

  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.prom
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - monitor-net
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus

  alertmanager:
    build:
      context: .
      dockerfile: Dockerfile.alert
    container_name: alertmanager
    ports:
      - "9093:9093"
    networks:
      - monitor-net
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager


  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitor-net
